[package]
name = "Timeline"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.6"

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.33"
svg = "0.17.0"
thiserror = "1.0"
structopt = "0.3"
